# -*- coding: utf-8 -*-
"""python_code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HTlsvT7J05SzZcSZzcGAioZZSfb1BASG
"""

import pandas as pd

# Read an Excel file
df = pd.read_excel('company_data.xlsx')
df

df.head(5)

df.tail(5)

df.info()

df.describe()

df['Manufacturer'].value_counts()

df['Product Category'].value_counts()

df['Country'].value_counts()

df[df['Product Name']=='Contoso DVD 9-Inch Player Portable M300 Silver']['Profit']

df[df['Product Name']=='NT Bluetooth Stereo Headphones E52 Pink']['Sales']

df[df['Profit']== df['Profit'].max()]['Product Name']

df[df['Sales']== df['Sales'].max()]['Product Name']

df[df['Sales']== df['Sales'].max()]

df[df['Profit']== df['Profit'].min()]['Product Name']

df[df['Profit']== df['Profit'].min()]

df[df['Sales']== df['Sales'].min()]['Product Name']

# Group data by 'Product Category' and calculate total sales and profits for each category
df.groupby('Product Category').agg({'Sales': 'sum', 'Profit': 'sum'})

# Find the top-selling products
df.groupby('Product Name')['Sales'].sum().nlargest(10)

# Calculate average sales per order
df['Sales'].mean()

# Calculate averag profit per order
df['Profit'].mean()

# Calculate total sales and profit for each region
df.groupby('Region').agg({'Sales': 'sum', 'Profit': 'sum'})